### PR TITLE
Use sccache to speed up CI

### PR DESCRIPTION
**Pull request by huitseeker**
Use sccache to speed up testing in CI.

### CODE REVIEW

**Comment by huitseeker** [comment]
End of [script](https://travis-ci.org/scipr-lab/zexe/builds/642103957?utm_source=github_status&utm_medium=notification):
```
0.01s$ sccache -s
Compile requests                     39
Compile requests executed            31
Cache hits                            0
Cache misses                         31
Cache misses (Rust)                  31
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   8
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.867 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Non-cacheable reasons:
incremental                           6
crate-type                            2
Cache location                  Local disk: "/home/travis/.cache/sccache"
Cache size                           84 MiB
Max cache size                      200 MiB
```

**Comment by Pratyush** [comment]
btw, @huitseeker , is it possible to build `sccache` statically and cache the binary, or to install it via a package? Currently `cargo install sccache` itself adds 9 mins to the CI time

**Comment by kobigurk** [comment]
We could potentially create a base image that contains it, if no other
options exist.

**Comment by huitseeker** [comment]
@Pratyush It's saved in the cargo cache, see:
https://travis-ci.org/scipr-lab/zexe/jobs/642453582?utm_medium=notification&utm_source=github_status
(and https://github.com/scipr-lab/zexe/pull/77 for the fix)

**Pull request merged**
