### PR TITLE
Test + Affine SW refactoring

### PR DESCRIPTION
**Pull request by jon-chuang**
Refactored to reduce code duplication, largely using macros. Further, feature gates all tests by type. 

The majority of the file changes is happening in 3 files (bn254 and both bls12 field tests) with lots of manual tests that cannot be refactored (3100 loc). In the remainder, we reduce about 1800 loc to about 1400. The major improvement is that a majority of the tests can be controlled by single macros/functions, rather than copy-pasta in 10s of files.

---
1/3 of a series of PRs to scipr-lab/zexe.

Features:
- Batch Affine ops
- Batch and ordinary w-NAF
- GLV framework, params only for bw6. GLV precomputation script.
- GLV impl for both batch affine and projective mul
- Batch bucket addition tree
- Batched MSM (1.4-1.7x bump)
- Batch subgroup verification based on addition to random buckets
- 2D test matrix feature-gating with axes (curve, test type)
- Refactor tests to use common template
- Code timing instrumentation with fine grained control of functions and callers

Combined speedup (with w-NAF) for
- Batched mul (with GLV): 2.3-2.7x. 
- Non-batch projective mul (with GLV): 2.1x.
Without GLV: 1.65-1.8x and 1.4x resp.

Speedup for subgroup verification
- Over old impl 25-80x.
- Over new batch mul: 10-30x.

### CODE REVIEW

**Comment by jon-chuang** [comment]
@Pratyush do you think we could get this merged? This particular PR is quite straightforward, further, it's been reviewed before on celo-org/zexe

**Comment by Pratyush** [comment]
Hey @jon-chuang sorry, we've been doing a refactor of the organization of the repo. The algebra related refactor is [here](https://github.com/arkworks-rs/algebra). If you could rebase atop that, that would be awesome. Otherwise, porting over the changes to a fresh branch should be straightforward too.

**Comment by Pratyush** [comment]
Hey @jon-chuang, thanks for the PR!
As I mentioned above, we're transitioning the code in this repo over to https://github.com/arkworks-rs/algebra/; could you make the PR there instead? There might be some conflicts because we've broken apart algebra into `ark-ff` and `ark-ec`.

**Comment by Pratyush** [comment]
Hi @jon-chuang do you mind re-opening this PR against arkworks-rs/algebra and against arkworks-rs/curves? 

(It'll probably be quite a rework, sorry for the inconvenience!)

**Pull request closed without merging**
